"""Provider-neutral SemanticVideo schema models."""

from semanticvideo.schema.annotation import (
    Annotation,
    AnnotationStatus,
    AudioAnnotation,
    AudioContentType,
    AudioInfo,
    CustomAnnotation,
    EditingSignals,
    EditorialAnnotation,
    EventAnnotation,
    EventInfo,
    GeoPoint,
    LocationAnnotation,
    LocationInfo,
    QualityAnnotation,
    QualityMetrics,
    SceneAnnotation,
    SceneInfo,
    SpatialRegion,
    SpeechAnnotation,
    SpeechInfo,
    SpeechWord,
    SubjectAnnotation,
    SubjectInfo,
)
from semanticvideo.schema.document import (
    AnalysisRun,
    Artifact,
    CapabilityReport,
    CapabilityStatus,
    SegmentRelation,
    SegmentRelationType,
    SemanticVideoDocument,
)
from semanticvideo.schema.edit import EditClip, EditPlan
from semanticvideo.schema.entity import Entity, EntityType
from semanticvideo.schema.media import (
    AudioStream,
    Checksum,
    MediaInfo,
    Stream,
    SubtitleStream,
    VideoStream,
)
from semanticvideo.schema.provenance import (
    Evidence,
    GeneratorInfo,
    Provenance,
    ProvenanceSource,
)
from semanticvideo.schema.segment import Segment, SegmentKind
from semanticvideo.schema.time import RationalRate, RationalTime, TimeRange

__all__ = [
    "AnalysisRun",
    "Annotation",
    "AnnotationStatus",
    "Artifact",
    "AudioAnnotation",
    "AudioContentType",
    "AudioInfo",
    "AudioStream",
    "CapabilityReport",
    "CapabilityStatus",
    "Checksum",
    "CustomAnnotation",
    "EditClip",
    "EditPlan",
    "EditingSignals",
    "EditorialAnnotation",
    "Entity",
    "EntityType",
    "EventAnnotation",
    "EventInfo",
    "Evidence",
    "GeneratorInfo",
    "GeoPoint",
    "LocationAnnotation",
    "LocationInfo",
    "MediaInfo",
    "Provenance",
    "ProvenanceSource",
    "QualityAnnotation",
    "QualityMetrics",
    "RationalRate",
    "RationalTime",
    "SceneAnnotation",
    "SceneInfo",
    "Segment",
    "SegmentKind",
    "SegmentRelation",
    "SegmentRelationType",
    "SemanticVideoDocument",
    "SpatialRegion",
    "SpeechAnnotation",
    "SpeechInfo",
    "SpeechWord",
    "Stream",
    "SubjectAnnotation",
    "SubjectInfo",
    "SubtitleStream",
    "TimeRange",
    "VideoStream",
]
