"""Public API for the SemanticVideo reference implementation."""

from semanticvideo.media import inspect_media, parse_ffprobe_json
from semanticvideo.schema import (
    AnalysisRun,
    Annotation,
    AnnotationStatus,
    Artifact,
    AudioStream,
    Checksum,
    CustomAnnotation,
    Entity,
    EntityType,
    EventAnnotation,
    EventInfo,
    Evidence,
    LocationAnnotation,
    LocationInfo,
    MediaInfo,
    Provenance,
    ProvenanceSource,
    QualityAnnotation,
    QualityMetrics,
    RationalRate,
    RationalTime,
    SceneAnnotation,
    SceneInfo,
    Segment,
    SegmentKind,
    SemanticVideoDocument,
    SpatialRegion,
    SpeechAnnotation,
    SpeechInfo,
    Stream,
    SubjectAnnotation,
    SubjectInfo,
    SubtitleStream,
    TimeRange,
    VideoStream,
)

__all__ = [
    "AnalysisRun",
    "Annotation",
    "AnnotationStatus",
    "Artifact",
    "AudioStream",
    "Checksum",
    "CustomAnnotation",
    "Entity",
    "EntityType",
    "EventAnnotation",
    "EventInfo",
    "Evidence",
    "LocationAnnotation",
    "LocationInfo",
    "MediaInfo",
    "Provenance",
    "ProvenanceSource",
    "QualityAnnotation",
    "QualityMetrics",
    "RationalRate",
    "RationalTime",
    "SceneAnnotation",
    "SceneInfo",
    "Segment",
    "SegmentKind",
    "SemanticVideoDocument",
    "SpatialRegion",
    "SpeechAnnotation",
    "SpeechInfo",
    "Stream",
    "SubjectAnnotation",
    "SubjectInfo",
    "SubtitleStream",
    "TimeRange",
    "VideoStream",
    "inspect_media",
    "parse_ffprobe_json",
]

__version__ = "0.1.0"
